#!/bin/sh

# Stop on errors
set -e

# Setting up gitconfig with alias
read -r "Enter your git username: " gitUsername
read -r "Enter your git email address: " gitEmail

echo "Setting your global git username to '$gitUsername'"
git config --global user.name "$gitUsername"
echo "Setting your global git email to '$gitEmail'"
git config --global user.email "$gitEmail"
