#!/bin/sh

# Stop on errors
set -e

# Install nvim if it does not exist
echo "Checking for nvim installation..."
nvimPath=$(which nvim)

# Checking to see if nvim path is registered
if [ $nvimPath -ne "/usr/bin/nvim" ]; then
  echo "Git not detected, installing git..."
  sudo apt install nvim
fi

# Copy neovim files to ~/.config/nvim
nvimPath="~/.config/nvim/"
mkdir -p $nvimPath
echo "Copying neovim files to $nvimPath"
cp -r nvim/* $nvimPath

# Ask to install neovide
read -p "Would you like to install NEOVIDE now? [Y,n]: " -i Y neovideReply
if [ $neovideReply -eq "y" || $neovideReply -eq "Y" ]; then
  # Install neovide
  echo "Installing prerequisites..."
  sudo apt install -y curl \
      gnupg ca-certificates git \
      gcc-multilib g++-multilib cmake libssl-dev pkg-config \
      libfreetype6-dev libasound2-dev libexpat1-dev libxcb-composite0-dev \
      libbz2-dev libsndio-dev freeglut3-dev libxmu-dev libxi-dev libfontconfig1-dev \
      libxcursor-dev

  # Use cargo to install neovide
  cargo install --git https://github.com/neovide/neovide

fi
