#!/bin/sh

# Stop on errors
set -e

# Copy local content to ~/.loca/share/
echo "Setting up bubbly..."

mkdir -p ~/local/share/bubbly
echo "Copying bubbly files to respective directories"
cp -r bubbles/local/* ~/.local/share/bubbly/

mkdir -p ~/.config/bubbly
cp -r bubbles/config/* ~/.config/bubbly/

# Register desktop application
echo "Registering desktop bubbly application"
cp -r bubbles/bubbly.desktop ~/.local/share/applications/

sleep 1

echo "Setup will now attempt to add you as member of the video group to allow you change screen brightness using the dashboard."
# Ask to accept adding to video group
read -p "Would you like setup to add you ro video group? [Y,n]: " -i Y videoResult
if [ $videoResult -eq "y" || $videoResult -eq "Y" ]; then
  # Add the user
  sudo gpasswd video -a $(whoami)

  # Add backlight rule to '/etc/udev/rules/' path
  sudo cp -r backlight.rules /etc/udev/rules.d/backlight.rules

  echo "User added. Setup will now continue with the remaining steps."
fi
