#!/bin/bash

# Check the current status of the keyboard backlight
status=$( xset q | grep 'Scroll Lock' | awk '{print $12}' )

# Toggle the backlight status 
if [ "$status" == "on" ]; then
  # If the backlight is on, turn it off
  xset -led
  # xset -led named 'Scroll Lock'
else
# If the backlight is off, turn it on
  xset led
  # xset led named 'Scroll Lock'
fi
